CREATE TABLE TIPO_DOCUMENTO
(
	CD_TIPO_DOCUMENTO	INT IDENTITY(1,1) PRIMARY KEY,
	DS_TIPO_DOCUMENTO	VARCHAR(50) NOT NULL
)

CREATE TABLE PESSOA_FISICA
(
	CD_PESSOA_FISICA	INT IDENTITY(1,1) PRIMARY KEY,
	NM_PESSOA_FISICA	VARCHAR(100) NOT NULL,
	DT_NASCIMENTO		DATETIME NOT NULL,
	DS_TELEFONE			VARCHAR(30),
	CD_TIPO_DOCUMENTO	INT FOREIGN KEY REFERENCES TIPO_DOCUMENTO(CD_TIPO_DOCUMENTO) NULL,
	VL_TIPO_DOCUMENTO	VARCHAR(50) NULL,
	IE_ATIVO			BIT NOT NULL DEFAULT 1,
	DT_ATUALIZACAO		DATETIME NOT NULL
)

