CREATE TABLE TIPO_DOCUMENTO
(
	CD_TIPO_DOCUMENTO	INT IDENTITY(1,1) PRIMARY KEY,
	DS_TIPO_DOCUMENTO	VARCHAR(50) NOT NULL
)

CREATE TABLE PESSOA_FISICA
(
	CD_PESSOA_FISICA	INT IDENTITY(1,1) PRIMARY KEY,
	NM_PESSOA_FISICA	VARCHAR(100) NOT NULL,
	DT_NASCIMENTO		DATETIME NOT NULL,
	DS_TELEFONE			VARCHAR(30),
	CD_TIPO_DOCUMENTO	INT FOREIGN KEY REFERENCES TIPO_DOCUMENTO(CD_TIPO_DOCUMENTO) NULL,
	VL_TIPO_DOCUMENTO	VARCHAR(50) NULL,
	IE_ATIVO			BIT NOT NULL DEFAULT 1,
	DT_ATUALIZACAO		DATETIME NOT NULL
)

CREATE TABLE MEDICO
(
	CRM_MEDICO			INT NOT NULL PRIMARY KEY,
	CD_PESSOA_FISICA	INT NOT NULL FOREIGN KEY REFERENCES PESSOA_FISICA(CD_PESSOA_FISICA),
	IE_ATIVO			BIT NOT NULL DEFAULT 1,
	DT_ATUALIZACAO		DATETIME NOT NULL
)

CREATE TABLE TIPO_ATENDIMENTO
(
	ID_TIPO_ATENDIMENTO	INT IDENTITY(1,1) PRIMARY KEY,
	DS_TIPO_ATENDIMENTO	VARCHAR(30) NOT NULL
)

CREATE TABLE ESPECIALIDADE_ATENDIMENTO
(
	ID_ESPECIALIDADE	INT IDENTITY(1,1) PRIMARY KEY,
	DS_ESPECIALIDADE	VARCHAR(100)
)

CREATE TABLE ATENDIMENTO_PACIENTE
(
	NR_ATENDIMENTO		INT IDENTITY(1,1) PRIMARY KEY,
	CD_PESSOA_FISICA	INT NOT NULL FOREIGN KEY REFERENCES PESSOA_FISICA(CD_PESSOA_FISICA),
	CRM_MEDICO			INT NOT NULL FOREIGN KEY REFERENCES MEDICO(CRM_MEDICO),
	ID_TIPO_ATENDIMENTO	INT NOT NULL FOREIGN KEY REFERENCES TIPO_ATENDIMENTO(ID_TIPO_ATENDIMENTO),
	ID_ESPECIALIDADE	INT NOT NULL FOREIGN KEY REFERENCES ESPECIALIDADE_ATENDIMENTO(ID_ESPECIALIDADE),
	DT_ATENDIMENTO		DATETIME NOT NULL,
	DS_OBSERVACAO		VARCHAR(600) NULL
)
