USE [ProntuarioUnico]
GO

/****** Object:  View [dbo].[PRONTUARIO]    Script Date: 02/12/2019 22:45:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[PRONTUARIO]
AS
SELECT 
	AP.NR_ATENDIMENTO, 
	AP.CD_PESSOA_FISICA, 
	TA.DS_TIPO_ATENDIMENTO, 
	AP.DT_ATENDIMENTO, 
	AP.CRM_MEDICO, 
	PF_M.NM_PESSOA_FISICA AS NM_MEDICO, 
	EA.DS_ESPECIALIDADE, 
	AP.DS_OBSERVACAO
FROM            
				dbo.ATENDIMENTO_PACIENTE		AS AP 
	INNER JOIN	dbo.MEDICO						AS M	ON AP.CRM_MEDICO			= M.CRM_MEDICO 
	INNER JOIN	dbo.PESSOA_FISICA				AS PF_M ON M.CD_PESSOA_FISICA		= PF_M.CD_PESSOA_FISICA 
	INNER JOIN	dbo.TIPO_ATENDIMENTO			AS TA	ON AP.ID_TIPO_ATENDIMENTO	= TA.ID_TIPO_ATENDIMENTO 
	INNER JOIN	dbo.ESPECIALIDADE_ATENDIMENTO	AS EA	ON AP.ID_ESPECIALIDADE		= EA.ID_ESPECIALIDADE
GO